{
 "title": "pfSense Demo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Services Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "services_status",
     "query": "SELECT  \"description\" as \"Description\", \"status\" as \"Status\" FROM \"services_status\" WHERE time > now() - 10s GROUP BY \"service\"",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gateway Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "services_status",
     "query": "SELECT \"name\" as \"Gateway\", \"rtt\" as \"RTT\", \"rttsd\" as \"RTT Standard Deviation\", \"status\" as \"Status\" FROM \"gateway_status\" WHERE time > now() - 10s ",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"name\" as \"Name\", \"packets_in\" as \"Packets In\", \"packets_out\" as \"Packets Out\", \"bytes_in\" as \"Bytes In\", \"bytes_out\" as \"Bytes Out\", \"errors_in\" as \"Errors In\", \"errors_out\" as \"Errors Out\", \"collisions\" as \"Collisions\" FROM \"interface_statistics\" WHERE time > now() - 10s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"name\" as \"Name\", \"ip_address\" as \"IP Address\", \"status\" as \"Status\" FROM \"interface_status\" WHERE time > now() - 10s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenVPN Clients",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"remote_host\" as \"Remote Host\", \"virtual_address\" as \"Virtual Address\", \"status\" as \"Status\" FROM \"openvpn_client_status\" WHERE time > now() - 10s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenVPN Connected Clients",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"common_name\" as \"Common Name\", \"remote_host\" as \"Remote Host\", \"virtual_address\" as \"Virtual Address\" FROM \"openvpn_connected_clients\" WHERE time > now() - 10s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenVPN Connected Clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "openvpn_connected_clients",
     "select": [
      [
       { "params": [ "connected_clients" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alerts Panel",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gateway_status",
     "query": "SELECT  \"status\" as \"Services Status\" FROM \"services_status\" WHERE time > now() - 10s GROUP BY \"service\"",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openvpn_client_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "services_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}